### ISSUE TITLE
Empty dashboard

### ISSUE THREAD

**Issue by suntong** [testsmith-io/jmeter-influxdb-grafana-docker#1]
Thank you for providing this turn-key solution first of all. 

If I follow the readme and run `./run-specific-jmeter-script.sh example.jmx` as-is without modifying anything, would I get something out from the dashboard?

I'm getting an empty dashboard FYI:

<img width="903" alt="image" src="https://user-images.githubusercontent.com/422244/179071332-055d3e6b-6c1b-421b-b375-0407cb5bdbc3.png">

Even though everything seems to be working fine:

```sh
$ ./run-specific-jmeter-script.sh example.jmx
START Running Jmeter on Thu Jul 14 21:42:17 CEST 2022
JVM_ARGS=-Xmn5928m -Xms23712m -Xmx23712m
jmeter args=-n -t /mnt/jmeter/example.jmx -JINFLUXDB_HOST=host.docker.internal -l /mnt/jmeter/results/result_20220714_154216.jtl -j /mnt/jmeter/results/jmeter_20220714_154216.log
Jul 14, 2022 9:42:18 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Creating summariser <summary>
Created the tree successfully using /mnt/jmeter/example.jmx
Starting standalone test @ Thu Jul 14 21:42:18 CEST 2022 (1657827738809)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +      7 in 00:00:12 =    0.6/s Avg:    55 Min:    42 Max:    83 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
summary +     19 in 00:00:30 =    0.6/s Avg:    52 Min:    40 Max:   128 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
summary =     26 in 00:00:41 =    0.6/s Avg:    53 Min:    40 Max:   128 Err:     0 (0.00%)
summary +     14 in 00:00:23 =    0.6/s Avg:    77 Min:    44 Max:   413 Err:     0 (0.00%) Active: 0 Started: 1 Finished: 1
summary =     40 in 00:01:04 =    0.6/s Avg:    61 Min:    40 Max:   413 Err:     0 (0.00%)
Tidying up ...    @ Thu Jul 14 21:43:23 CEST 2022 (1657827803708)
... end of run
END Running Jmeter on Thu Jul 14 21:43:24 CEST 2022
```

Is there anything that I need to change in order to make things working pleaes?

For e.g., do I need to change the `host.docker.internal` in the `run-specific-jmeter-script.sh`?

```
$ ping host.docker.internal
ping: host.docker.internal: Name or service not known
```

Or do I need to open the `:8086` port to the public?
Or maybe I need to setup influxdb?

thx

**Comment by HDTestAccount** [comment]
You need set in influx backend listener influxhost - influx, and add network of influx container to jmeter container. And it work fine.
Or use for backend listener external IP or hostname of your docker host

**Comment by suntong** [comment]
> You need 
> 1. set in influx backend listener influxhost - influx, and 
> 1. add network of influx container to jmeter container

So for point 1, the influx backend listener is listening to this:

https://github.com/testsmith-io/jmeter-influxdb-grafana-docker/blob/357192db5b66cc7dbe73d361a68cc54f032c3840/jmeter-scripts/example.jmx#L151

And I've removed this line:

https://github.com/testsmith-io/jmeter-influxdb-grafana-docker/blob/357192db5b66cc7dbe73d361a68cc54f032c3840/run-jmeter.sh#L11

So the effect would be that the JMeter script would be sending through influx backend listener and localhost:8086 to `jmeter_results` right?

But I'm still getting an empty dashboard. What have I been missing please?

Oh, maybe point 2, _"add network of influx container to jmeter container"_. How can I do that please?

**Comment by suntong** [comment]
> Or do I need to open the `:8086` port to the public?

So I open the `:8086` port to intranet, but when visiting it, I got `404 page not found`. Is that what supposed to be?

**UPDATE:**

I now think that 404 error might be the root cause of all above, as when visiting via intranet to `:3000`, the connection is good. As shown in OP.

My understanding is that it means the end listening port for backend listener is not functioning properly, which is also the reason why I'm getting `failed to send data to influxDB server` in my jmeter's log.

**Comment by suntong** [comment]
> And it work fine.

I tried again today and it is working now. I didn't anything. strange.

**Comment by suntong** [comment]
> I tried again today and it is working now. I didn't anything. strange.

Gee. I thought I saw it working, but having done `docker-compose down` and `docker-compose up -d` again, 

- there isn't any history run result in the dashboard
- and when I run another one, dashboard still basically has no data (long after the test is finished) --

<img width="930" alt="image" src="https://user-images.githubusercontent.com/422244/179284725-5a7d5112-0722-4a20-b647-f00178d414e9.png">

This time, I'm sure that I didn't do anything.

**Comment by testsmith-io** [comment]
Hello @suntong, I'm glad it worked for you!
